version: "3.9"

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "8501:8501"
    volumes:
      - ./data:/app/data  # pour accéder au fichier DuckDB
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data  # pour accéder au même fichier DuckDB
    networks:
      - app-network

  duckdb:
    image: alpine  # juste un conteneur vide pour représenter la base via volume
    volumes:
      - ./data:/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
